language: java

script:
  - cd lab1/Lab1
  - ant gen
  - ant build
  - ant LexerTests
  - cd ../../lab2/Lab2
  - ant parser
  - ant build
  - ant ParserTests

notifications:
  email:
    on_success: never
    on_failure: never
